#use_frameworks!
pod 'AFNetworking'

target 'TLProgressSpring_Example' do
  pod 'TLProgressSpring', :path => '../'


  target 'TLProgressSpring_Tests' do
    #inherit! :search_paths

    pod 'Kiwi'
  end
end
